/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_manuelvalladares;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author mevl1
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elegir = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        peliculas = new javax.swing.JDialog();
        tf_n = new javax.swing.JTextField();
        tf_dur = new javax.swing.JTextField();
        tf_prod = new javax.swing.JTextField();
        tf_act = new javax.swing.JTextField();
        tf_dir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_cat = new javax.swing.JComboBox<>();
        cb_idio = new javax.swing.JComboBox<>();
        cb_dob = new javax.swing.JComboBox<>();
        cb_subs = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        SERIE = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        dur = new javax.swing.JTextField();
        prod = new javax.swing.JTextField();
        act = new javax.swing.JTextField();
        temp = new javax.swing.JTextField();
        id = new javax.swing.JComboBox<>();
        dob = new javax.swing.JComboBox<>();
        subs = new javax.swing.JComboBox<>();
        cat = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jd_arbol = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();

        jButton2.setText("pelicula");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("serie");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton6.setText("VER ARBOL");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout elegirLayout = new javax.swing.GroupLayout(elegir.getContentPane());
        elegir.getContentPane().setLayout(elegirLayout);
        elegirLayout.setHorizontalGroup(
            elegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elegirLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(107, 107, 107))
            .addGroup(elegirLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        elegirLayout.setVerticalGroup(
            elegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elegirLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(elegirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(64, 64, 64)
                .addComponent(jButton6)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jLabel4.setText("nombre");

        jLabel5.setText("duracion");

        jLabel6.setText("categoria");

        jLabel7.setText("actores");

        jLabel8.setText("director");

        jLabel9.setText("productora");

        jLabel10.setText("idioma");

        jLabel11.setText("doblaje");

        jLabel12.setText("subtitulos");

        cb_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suspenso", "Terror", "Accion", "Romanticas", "Scy-fi", "Animacion", "Fantasia" }));

        cb_idio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingles", "Español", "Frances" }));

        cb_dob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no" }));

        cb_subs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no" }));

        jButton4.setText("agregar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout peliculasLayout = new javax.swing.GroupLayout(peliculas.getContentPane());
        peliculas.getContentPane().setLayout(peliculasLayout);
        peliculasLayout.setHorizontalGroup(
            peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peliculasLayout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(peliculasLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(peliculasLayout.createSequentialGroup()
                            .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(62, 62, 62)
                            .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_n)
                                .addComponent(tf_dur)
                                .addComponent(tf_act)
                                .addComponent(tf_dir, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(peliculasLayout.createSequentialGroup()
                            .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(peliculasLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peliculasLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(77, 77, 77)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peliculasLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(72, 72, 72)))
                            .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_prod)
                                    .addComponent(cb_idio, 0, 201, Short.MAX_VALUE))
                                .addComponent(cb_subs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(641, Short.MAX_VALUE))
        );
        peliculasLayout.setVerticalGroup(
            peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peliculasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(peliculasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(peliculasLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_idio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cb_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cb_subs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jLabel13.setText("nombre");

        jLabel14.setText("duracion");

        jLabel15.setText("categoria");

        jLabel16.setText("actores");

        jLabel17.setText("temporadas");

        jLabel18.setText("productora");

        jLabel19.setText("idioma");

        jLabel20.setText("doblaje");

        jLabel21.setText("subtitulos");

        id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ingles", "español", "frances" }));

        dob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no" }));

        subs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no" }));

        jButton5.setText("agregar+");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SERIELayout = new javax.swing.GroupLayout(SERIE.getContentPane());
        SERIE.getContentPane().setLayout(SERIELayout);
        SERIELayout.setHorizontalGroup(
            SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SERIELayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(35, 35, 35)
                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dur)
                        .addComponent(nom)
                        .addComponent(prod, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(act)
                        .addComponent(temp)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cat))
                    .addGroup(SERIELayout.createSequentialGroup()
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jButton5)))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        SERIELayout.setVerticalGroup(
            SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SERIELayout.createSequentialGroup()
                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SERIELayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SERIELayout.createSequentialGroup()
                                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(temp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel19))
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SERIELayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(7, 7, 7)))
                .addGroup(SERIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(subs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("NESFLIS");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_arbol);

        javax.swing.GroupLayout jd_arbolLayout = new javax.swing.GroupLayout(jd_arbol.getContentPane());
        jd_arbol.getContentPane().setLayout(jd_arbolLayout);
        jd_arbolLayout.setHorizontalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jd_arbolLayout.setVerticalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_arbolLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LogIn");

        jButton1.setText("INICIAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("USUARIO");

        jLabel3.setText("CONTRASEÑA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuario)
                            .addComponent(tf_contra)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       ADMIN_USUARIOS ad_u=new ADMIN_USUARIOS("./usuarios.txt");
       ad_u.cargarArchivo();
        for (USUARIO i : ad_u.getUsuarios()) {
            if (tf_usuario.getText().equals(i.getUser()) && tf_contra.getText().equals(i.getContra())) {
        elegir.setModal(true);
        elegir.pack();
        elegir.setLocationRelativeTo(this);
        elegir.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(this, "INCORRECTO");
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        ADMIN ad_u=new ADMIN("./peliculas.txt");
        ad_u.cargarArchivo();
        String nombre,duracion,categoria,actores,director,productora,idioma,doblaje,subs;
        nombre=tf_n.getText();
        duracion=tf_dur.getText();
        categoria=(String) cb_cat.getSelectedItem();
        actores=tf_act.getText();
        director=tf_dir.getText();
        productora=tf_prod.getText();
        idioma=(String) cb_idio.getSelectedItem();
        doblaje=(String) cb_dob.getSelectedItem();
        subs=(String) cb_subs.getSelectedItem();
        //String nombre, String duracion, String categoria, String actores, String director, String productora, String idioma, String doblaje, String subs
        ad_u.getPeliculas().add(new PELICULA(nombre,duracion,categoria,actores,director,productora,idioma,doblaje,subs));
        try {
            ad_u.escribirArchivo();
        } catch (IOException ex) {
        }
        
        
            DefaultTreeModel modeloARBOL=(DefaultTreeModel)jt_arbol.getModel();
            DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modeloARBOL.getRoot();
            DefaultMutableTreeNode k=new DefaultMutableTreeNode("PELICULAS");
            //obtener la persona a guardar
            int centinela=-1;
            for (PELICULA i : ad_u.getPeliculas()) {
            
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals(categoria)) {
                    DefaultMutableTreeNode p=new DefaultMutableTreeNode(new PELICULA(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getDirector(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubs()));
                    DefaultMutableTreeNode h=new DefaultMutableTreeNode("PELICULAS");
                ((DefaultMutableTreeNode)k.getChildAt(j)).add(p);
                centinela=1;
                }
            }
            if (centinela==-1) {
                DefaultMutableTreeNode n=new DefaultMutableTreeNode(categoria);
                DefaultMutableTreeNode p=new DefaultMutableTreeNode(new PELICULA(i.getNombre(), i.getDuracion(), i.getCategoria(), i.getActores(), i.getDirector(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubs()));
               DefaultMutableTreeNode h=new DefaultMutableTreeNode("PELICULAS");
                n.add(p);
                k.add(n);
                raiz.add(k);
            }
            modeloARBOL.reload();
        
        }
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        admin_series ad_u=new admin_series("./series.txt");
        ad_u.cargarArchivo();
        //String nombre, String duracion, String categorias, String actores, String temporadas, String productora, String idioma, String doblaje, String subs
        String nombre,duracion,categorias,actores,temporadas,productora,idioma,doblaje,subs;
        nombre=nom.getText();
        duracion=dur.getText();
        categorias=cat.getText();
        actores=act.getText();
        temporadas=temp.getText();
        productora=prod.getText();
        idioma=(String) id.getSelectedItem();
        doblaje=(String) dob.getSelectedItem();
        subs=(String) this.subs.getSelectedItem();
        ad_u.getSeries().add(new SERIE(nombre, duracion, categorias, actores, temporadas, productora, idioma, doblaje, subs));
        try {
            ad_u.escribirArchivo();
        } catch (IOException ex) {
        }
        DefaultTreeModel modeloARBOL=(DefaultTreeModel)jt_arbol.getModel();
            DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modeloARBOL.getRoot();
            DefaultMutableTreeNode k=new DefaultMutableTreeNode("SERIES");
            //obtener la persona a guardar
            int centinela=-1;
            for (SERIE i : ad_u.getSeries()) {
            
            for (int j = 0; j < raiz.getChildCount(); j++) {
                if (raiz.getChildAt(j).toString().equals(categorias)) {
                    DefaultMutableTreeNode p=new DefaultMutableTreeNode(new SERIE(i.getNombre(), i.getDuracion(), i.getCategorias(), i.getActores(), i.getTemporadas(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubs()));
                ((DefaultMutableTreeNode)k.getChildAt(j)).add(p);
                centinela=1;
                }
            }
            if (centinela==-1) {
                DefaultMutableTreeNode n=new DefaultMutableTreeNode(categorias);
                DefaultMutableTreeNode p=new DefaultMutableTreeNode(new SERIE(i.getNombre(), i.getDuracion(), i.getCategorias(), i.getActores(), i.getTemporadas(), i.getProductora(), i.getIdioma(), i.getDoblaje(), i.getSubs()));
                DefaultMutableTreeNode h=new DefaultMutableTreeNode("SERIES");
                n.add(p);
                k.add(n);
                raiz.add(k);
            }
            modeloARBOL.reload();
        
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        peliculas.setModal(true);
        peliculas.pack();
        peliculas.setLocationRelativeTo(this);
        peliculas.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        SERIE.setModal(true);
        SERIE.pack();
        SERIE.setLocationRelativeTo(this);
        SERIE.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        
      jd_arbol.setModal(true);
      jd_arbol.pack();
      jd_arbol.setLocationRelativeTo(this);
      jd_arbol.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog SERIE;
    private javax.swing.JTextField act;
    private javax.swing.JTextField cat;
    private javax.swing.JComboBox<String> cb_cat;
    private javax.swing.JComboBox<String> cb_dob;
    private javax.swing.JComboBox<String> cb_idio;
    private javax.swing.JComboBox<String> cb_subs;
    private javax.swing.JComboBox<String> dob;
    private javax.swing.JTextField dur;
    private javax.swing.JDialog elegir;
    private javax.swing.JComboBox<String> id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_arbol;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTextField nom;
    private javax.swing.JDialog peliculas;
    private javax.swing.JTextField prod;
    private javax.swing.JComboBox<String> subs;
    private javax.swing.JTextField temp;
    private javax.swing.JTextField tf_act;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_dir;
    private javax.swing.JTextField tf_dur;
    private javax.swing.JTextField tf_n;
    private javax.swing.JTextField tf_prod;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
